### ISSUE TITLE
Errors when running for fedjeosen: resturcture_xr branch

### ISSUE THREAD

**Issue by gauteh** [bohlinger/wavy#48]
```
❯ python sat.py
# -----
 ### Initializing insitu_class object ###

 Given kwargs:
{'nID': 'fedjeosen', 'name': 'SFY', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'varalias': 'Hs'}
Chosen period: 2023-07-01 00:00:00 - 2023-10-04 00:00:00

 ### insitu_class object initialized ###
# -----
 ### Read files and populate insitu_class object
 ## Find and list files based on given path...
1 valid files found

Choosing reader..
#
Environmental variable for WAVY_DIR not defined
Defaults are chosen
#
Chosen reader: insitu_readers.get_nc_thredds_static_coords_single_file

Reading..
 Get filevarname for
stdvarname: sea_surface_wave_significant_height
varalias: Hs
 Variable defined in *_cfg.yaml is:
Hs = hm0
 Get filevarname for
stdvarname: longitude
varalias: lons
 !!! variable not defined nor available in nc-file !!!
 Get filevarname for
stdvarname: latitude
varalias: lats
 !!! variable not defined nor available in nc-file !!!
 Get filevarname for
stdvarname: time
varalias: time
 Variable defined in *_cfg.yaml is:
time = time
 Get filevarname for
stdvarname: sea_surface_wave_significant_height
varalias: Hs
 Variable defined in *_cfg.yaml is:
Hs = hm0
 Get filevarname for
stdvarname: time
varalias: time
 Variable defined in *_cfg.yaml is:
time = time
/home/gauteh/met/misc/wavy/wavy/insitu_module.py:351: UserWarning: rename 'time' to 'time' does not create an index anymore. Try using swap_dims instead or use set_index after rename to create an indexed coordinate.
  self.vars = self.vars.rename({ncvar: c})\
 Get filevarname for
stdvarname: longitude
varalias: lons
 !!! variable not defined nor available in nc-file !!!
ERROR:wavy.insitu_module:cannot rename None because it is not a variable or dimension in this dataset
Traceback (most recent call last):
  File "/home/gauteh/met/misc/wavy/wavy/insitu_module.py", line 351, in _change_varname_to_aliases
    self.vars = self.vars.rename({ncvar: c})\
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauteh/.mconda3/envs/sfy/lib/python3.11/site-packages/xarray/core/dataset.py", line 3737, in rename
    return self._rename(name_dict=name_dict, **names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauteh/.mconda3/envs/sfy/lib/python3.11/site-packages/xarray/core/dataset.py", line 3678, in _rename
    raise ValueError(
ValueError: cannot rename None because it is not a variable or dimension in this dataset
 Get filevarname for
stdvarname: latitude
varalias: lats
 !!! variable not defined nor available in nc-file !!!
ERROR:wavy.insitu_module:cannot rename None because it is not a variable or dimension in this dataset
Traceback (most recent call last):
  File "/home/gauteh/met/misc/wavy/wavy/insitu_module.py", line 351, in _change_varname_to_aliases
    self.vars = self.vars.rename({ncvar: c})\
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauteh/.mconda3/envs/sfy/lib/python3.11/site-packages/xarray/core/dataset.py", line 3737, in rename
    return self._rename(name_dict=name_dict, **names)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gauteh/.mconda3/envs/sfy/lib/python3.11/site-packages/xarray/core/dataset.py", line 3678, in _rename
    raise ValueError(
ValueError: cannot rename None because it is not a variable or dimension in this dataset

 ## Summary:
6487 values retrieved.
Time used for retrieving data:
4.94 seconds

 ### insitu_class object populated ###
# -----
# -----
 ### Initializing poi_class object ###

 Given kwargs:
{'nID': 'fedjeosen', 'name': 'SFY', 'varalias': 'Hs'}
Chosen period: 2023-07-01 00:21:08.772900 - 2023-10-03 22:58:22.457382

 ### insitu_class object initialized ###
# -----
# -----
 ### Initializing satellite_class object ###

 Given kwargs:
{'nID': 'cmems_L3_NRT', 'name': 's3a', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'region': 'fedjeosen'}

 ### satellite_class object initialized ###
# -----
# -----
 ### Initializing satellite_class object ###

 Given kwargs:
{'nID': 'cmems_L3_NRT', 'name': 's3b', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'region': 'fedjeosen'}

 ### satellite_class object initialized ###
# -----
# -----
 ### Initializing satellite_class object ###

 Given kwargs:
{'nID': 'cmems_L3_NRT', 'name': 'c2', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'region': 'fedjeosen'}

 ### satellite_class object initialized ###
# -----
# -----
 ### Initializing satellite_class object ###

 Given kwargs:
{'nID': 'cmems_L3_NRT', 'name': 'j3', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'region': 'fedjeosen'}

 ### satellite_class object initialized ###
# -----
# -----
 ### Initializing satellite_class object ###

 Given kwargs:
{'nID': 'cmems_L3_NRT', 'name': 'h2b', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'region': 'fedjeosen'}

 ### satellite_class object initialized ###
# -----
# -----
 ### Initializing satellite_class object ###

 Given kwargs:
{'nID': 'cmems_L3_NRT', 'name': 'cfo', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'region': 'fedjeosen'}

 ### satellite_class object initialized ###
# -----
# -----
 ### Initializing satellite_class object ###

 Given kwargs:
{'nID': 'cmems_L3_NRT', 'name': 'al', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'region': 'fedjeosen'}

 ### satellite_class object initialized ###
# -----
# -----
 ### Initializing satellite_class object ###

 Given kwargs:
{'nID': 'cmems_L3_NRT', 'name': 's6a', 'sd': '2023-07-01', 'ed': '2023-10-04 ', 'region': 'fedjeosen'}

 ### satellite_class object initialized ###
# -----
 ### Read files and populate satellite_class object
 ## Find and list files ...
path is None -> checking config file
Object is iterable
0 valid files found
source template: /home/patrikb/tmp_altimeter/L3/name/%Y/%m

Checking variables..
Traceback (most recent call last):
  File "/home/gauteh/met/papers/sfy-paper/data/2023-fedjeosen/sat.py", line 50, in <module>
    s3a = s3a.populate().crop_to_poi(poi=pco, distlim=100, twin=10)
          ^^^^^^^^^^^^^^
  File "/home/gauteh/met/misc/wavy/wavy/satellite_module.py", line 494, in populate
    self.meta = ncdumpMeta(self.pathlst[0])
                           ~~~~~~~~~~~~^^^
IndexError: list index out of range

```

**Comment by bohlinger** [comment]
This should be fixed now, I hope.
