### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by vic1309** [bohlinger/wavy#70]
Hey,

I am following one of the tutorials on the wavy website (https://wavyopen.readthedocs.io/en/latest/tutorials_satmod.html), but the download can't be completed.

I created a .netrc file containing my login information, set the config files in my project folder, and adjusted the path_template in the satellite_specs.yaml file. I get the following error message:

[IN]:  ./wavyDownload.py -sat s3a -sd 2020110100 -ed 2020111000 -path /home/victorm/wavy/test_project/tmp_altimeter/L3/ -product cmems_L3_NRT

[OUT] ./wavyDownload.py -sat s3a -sd 2020110100 -ed 2020111000 -path /home/victorm/wavy/test_project/tmp_altimeter/L3/ -product cmems_L3_NRT -nproc 4
Namespace(sd='2020110100', ed='2020111000', sat='s3a', path='/home/victorm/wavy/test_project/tmp_altimeter/L3/', product='cmems_L3_NRT', api_url=None, nproc=4)
Attempting to download data for: s3a
Time period: 2020-11-01 00:00:00 to 2020-11-10 00:00:00
Obtaining credentials from .netrc
# ----- 
Chosen source: 
s3a values from cmems_L3_NRT: nrt.cmems-du.eu
/Core/WAVE_GLO_PHY_SWH_L3_NRT_014_001/cmems_obs-wave_glo_phy-swh_nrt_s3a-l3_PT1S/2020/11/
# ----- 
Traceback (most recent call last):
  File "/home/victorm/wavy/apps/standalone/./wavyDownload.py", line 155, in <module>
    main()
  File "/home/victorm/wavy/apps/standalone/./wavyDownload.py", line 137, in main
    sa_obj = get_remote_files(\
             ^^^^^^^^^^^^^^^^^^
  File "/home/victorm/wavy/wavy/sat_collectors.py", line 440, in get_remote_files
    dispatch_collector[product](**kwargs)
  File "/home/victorm/wavy/wavy/sat_collectors.py", line 119, in get_remote_files_cmems
    ftp = FTP(server)
          ^^^^^^^^^^^
  File "/home/victorm/mambaforge/envs/wavy/lib/python3.11/ftplib.py", line 121, in __init__
    self.connect(host)
  File "/home/victorm/mambaforge/envs/wavy/lib/python3.11/ftplib.py", line 158, in connect
    self.sock = socket.create_connection((self.host, self.port), self.timeout,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/victorm/mambaforge/envs/wavy/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/home/victorm/mambaforge/envs/wavy/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

Tips?

**Comment by bohlinger** [comment]
Hi, this is because the wavy master is not yet updated to the cmems api. Let’s discuss this tomorrow in the meeting.
